sudo: required
services:
  - docker
language: python
python:
  - "3.5"
before_install:
  - tests/docker/nginx/build.sh
# command to install dependencies
install:
  - pip install tox-travis
  - pip install -e .
  - chmod ugo+x demo.sh
# command to run tests
script: ./demo.sh
